/*
 * This source file was generated by the Gradle 'init' task
 */
package sdplearningmaterial;

public class Client {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new Client().getGreeting());
    }
}
